name: Build e implantar aplicativo ASP.Net Core no Azure Web App - entrega-segura-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: entrega-segura-api
  AZURE_WEBAPP_PACKAGE_PATH: './publish'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_PORT: 5000 
      
    steps:
      - name: Verificar código
        uses: actions/checkout@v2

      - name: Configurar .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Restaurar dependências
        run: dotnet restore ./EntregaSegura.sln
        working-directory: ${{ github.workspace }}/Back

      - name: Compilar
        run: dotnet build ./EntregaSegura.sln --configuration Release --no-restore
        working-directory: ${{ github.workspace }}/Back

      - name: Publicar
        run: |
          dotnet publish ./EntregaSegura.sln --configuration Release --no-build --output ${{ github.workspace }}/Back/publish
          ls -R ${{ github.workspace }}/Back/publish  # Listar o conteúdo do diretório de publicação para fins de solução de problemas
        working-directory: ${{ github.workspace }}/Back

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Produção'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Implantação
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C79E23B27E8C4FC8907770B06B618502 }}
          package: .
