name: Build and deploy ASP.Net Core app to Azure Web App - entrega-segura-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: entrega-segura-api
  AZURE_WEBAPP_PACKAGE_PATH: './publish'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '6.0.x'

      - name: Restore
        run: dotnet restore ./EntregaSegura.sln
        working-directory: ${{ github.workspace }}/Back

      - name: Build
        run: dotnet build ./EntregaSegura.sln --configuration Release --no-restore
        working-directory: ${{ github.workspace }}/Back

      - name: Publish
        run: dotnet publish ./EntregaSegura.sln --configuration Release --no-build --output ${{ github.workspace }}/Back/publish
        working-directory: ${{ github.workspace }}/Back

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C79E23B27E8C4FC8907770B06B618502 }}
          package: ${{ github.workspace }}/Back/publish
